### ISSUE TITLE
Create logo for KA modular furniture

### ISSUE THREAD

**Issue by paragasu** [phisoft/kamodularfurniture-web#1]
KA modular funinture is a company making square bookcase that can be stack on each other to build complex bookshelf

**Comment by judithasitiol** [comment]
Sketches of KA modular furniture logo @paragasu 
![image](https://user-images.githubusercontent.com/24267254/144777246-75531026-4cba-4ef1-b279-5804e5a48631.png)

**Comment by judithasitiol** [comment]
[KAlogo.zip](https://github.com/phisoft/kamodularfurniture-web/files/7681746/KAlogo.zip)
@paragasu
